modules/backend/src/main/scala/docspell/backend/ops/OItem.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/ItemRoutes.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/DetailEdit.elm
modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Data/Icons.elm
modules/webapp/src/main/elm/Page/ManageData/View.elm
modules/webapp/src/main/elm/Util/Tag.elm

Add data while edit item

---

modules/common/src/main/scala/docspell/common/Duration.scala
modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/Config.scala
modules/joex/src/main/scala/docspell/joex/process/FindProposal.scala
modules/joex/src/main/scala/docspell/joex/process/ProcessItem.scala
modules/store/src/main/resources/db/migration/mariadb/V1.7.1__fix_item_date.sql
nix/module-joex.nix
nix/module-server.nix

Date columns

---

modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/scala/docspell/store/impl/Column.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala
modules/store/src/main/scala/docspell/store/records/TagItemName.scala
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Comp/UiSettingsForm.elm
modules/webapp/src/main/elm/Util/Tag.elm

Fixes #203 
Adds entries to the search menu, to allow to search by tag categories.

Tag category search

---

modules/backend/src/main/scala/docspell/backend/ops/OEquipment.scala
modules/backend/src/main/scala/docspell/backend/ops/OOrganization.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/EquipmentRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/OrganizationRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/PersonRoutes.scala
modules/store/src/main/scala/docspell/store/queries/QOrganization.scala
modules/store/src/main/scala/docspell/store/records/TagItemName.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/ContactField.elm
modules/webapp/src/main/elm/Comp/DetailEdit.elm
modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/OrgForm.elm
modules/webapp/src/main/elm/Comp/PersonForm.elm
modules/webapp/src/main/webjar/docspell.css

Add meta modal

---

modules/webapp/src/main/elm/Comp/FieldListSelect.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Comp/UiSettingsForm.elm
modules/webapp/src/main/elm/Data/Fields.elm
modules/webapp/src/main/elm/Data/UiSettings.elm

Allow to hide fields in menus based on ui settings

---

modules/common/src/main/scala/docspell/common/LenientUri.scala
modules/restserver/src/main/scala/docspell/restserver/auth/CookieData.scala
modules/restserver/src/main/scala/docspell/restserver/routes/LoginRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/webapp/Flags.scala
modules/webapp/src/main/elm/App/Data.elm

Base url confusion

---

elm.json
modules/webapp/src/main/elm/App/Data.elm
modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/App/View.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Page.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/Home/Update.elm
modules/webapp/src/main/elm/Page/Home/View.elm
modules/webapp/src/main/elm/Page/ItemDetail/Data.elm
modules/webapp/src/main/elm/Page/ItemDetail/Update.elm
modules/webapp/src/main/elm/Page/Login/Update.elm
modules/webapp/src/main/elm/Page/Upload/View.elm
modules/webapp/src/main/elm/Ports.elm
modules/webapp/src/main/webjar/docspell.css
modules/webapp/src/main/webjar/docspell.js

Scrolling bug

---

modules/webapp/src/main/elm/Page/Home/Update.elm

Move field contents when switching search mode in search bar

---

tools/consumedir.sh

Fix consumedir to handle files/directories with spaces

---

modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Page/ItemDetail/Update.elm
modules/webapp/src/main/elm/Page/ManageData/View.elm

Hidden fields fix

---

modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Page/ItemDetail/Data.elm
modules/webapp/src/main/elm/Page/ItemDetail/Update.elm

Save name in item detail while typing

---

modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Comp/FixedDropdown.elm
modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/KeyInput.elm
modules/webapp/src/main/elm/Comp/UiSettingsForm.elm
modules/webapp/src/main/elm/Data/ItemNav.elm
modules/webapp/src/main/elm/Data/UiSettings.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/ItemDetail/Update.elm
modules/webapp/src/main/elm/Page/ItemDetail/View.elm
modules/webapp/src/main/elm/Util/Html.elm

Keyboard support

---

modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
modules/common/src/main/scala/docspell/common/ProcessItemArgs.scala
modules/joex/src/main/scala/docspell/joex/process/DuplicateCheck.scala
modules/joex/src/main/scala/docspell/joex/process/ItemHandler.scala
modules/joex/src/main/scala/docspell/joex/process/ReProcessItem.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/scala/docspell/store/records/RFileMeta.scala
modules/webapp/src/main/elm/Page/Upload/Data.elm
modules/webapp/src/main/elm/Page/Upload/Update.elm
modules/webapp/src/main/elm/Page/Upload/View.elm

Duplicate upload

---

modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala

Skip invalid dates find in texts

---

modules/webapp/src/main/elm/App/Data.elm
modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/App/View.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Main.elm
modules/webapp/src/main/elm/Page.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/Home/Update.elm
modules/webapp/src/main/elm/Page/Home/View.elm
modules/webapp/src/main/elm/Page/Login/Update.elm
modules/webapp/src/main/elm/Page/Upload/View.elm

Fix detail links

---

modules/store/src/main/scala/docspell/store/impl/Column.scala
modules/store/src/main/scala/docspell/store/records/RTag.scala
modules/webapp/src/main/elm/Comp/DetailEdit.elm

Fix save existing tag

---

tools/import-paperless/import-paperless.sh

- moved auth header to curl_call to fix the infinite loop when re-login was necessary
- also restructured tiny bits

import-paperless: fixed problems with session timeout

---

tools/import-paperless/import-paperless.sh

be aware, all metadata will be overwritten (if document already exists in Docspell and has metadata set):
* tags
* organization
* title
* creation date

paperless import (v0.2 beta): also transferring title and creation date

---

modules/store/src/main/resources/db/migration/h2/V1.9.4__unique_equipments.sql
modules/store/src/main/resources/db/migration/mariadb/V1.9.4__unique_equipments.sql
modules/store/src/main/resources/db/migration/postgresql/V1.9.4__unique_equipments.sql

Add unique constraint for equipment names

---

modules/webapp/src/main/elm/Comp/UiSettingsManage.elm

Use previously updated ui settings

---

modules/backend/src/main/scala/docspell/backend/ops/OItem.scala
modules/joex/src/main/scala/docspell/joex/process/LinkProposal.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/restserver/src/main/scala/docspell/restserver/routes/ItemMultiRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/ItemRoutes.scala
modules/store/src/main/scala/docspell/store/impl/Column.scala
modules/store/src/main/scala/docspell/store/records/RItem.scala
modules/store/src/main/scala/docspell/store/records/RTagItem.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail/EditMenu.elm
modules/webapp/src/main/elm/Comp/ItemDetail/FormChange.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/YesNoDimmer.elm
modules/webapp/src/main/elm/Data/ItemSelection.elm
modules/webapp/src/main/elm/Data/Items.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/Home/Update.elm
modules/webapp/src/main/elm/Page/Home/View.elm
modules/webapp/src/main/webjar/docspell.css

Parallel edit

---

modules/common/src/main/scala/docspell/common/DocspellSystem.scala
modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/Config.scala
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/restserver/src/main/scala/docspell/restserver/routes/IntegrationEndpointRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/UploadRoutes.scala
nix/module-server.nix

Use source name from config file for integration endpoint uploads

---

modules/convert/src/main/scala/docspell/convert/extern/ExternConv.scala
modules/joex/src/main/scala/docspell/joex/pdfconv/PdfConvTask.scala
modules/joex/src/main/scala/docspell/joex/process/CreateItem.scala
modules/joex/src/main/scala/docspell/joex/process/ItemHandler.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala

Fixes the problem that a failure in pdf conversion resulted in aborting the processing alltogether. It now continues with the input file.

Fix process timeout

---

Changelog.md
modules/backend/src/main/scala/docspell/backend/ops/OItem.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/ItemMultiRoutes.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/ItemDetail/EditMenu.elm
modules/webapp/src/main/elm/Comp/ItemDetail/FormChange.elm

Fix multi tag edit

---

modules/backend/src/main/scala/docspell/backend/JobFactory.scala
modules/common/src/main/scala/docspell/common/DocspellSystem.scala
modules/common/src/main/scala/docspell/common/MakePageCountArgs.scala
modules/extract/src/main/scala/docspell/extract/pdfbox/PdfMetaData.scala
modules/extract/src/main/scala/docspell/extract/pdfbox/PdfboxExtract.scala
modules/joex/src/main/scala/docspell/joex/JoexAppImpl.scala
modules/joex/src/main/scala/docspell/joex/pagecount/AllPageCountTask.scala
modules/joex/src/main/scala/docspell/joex/pagecount/PageCountTask.scala
modules/joex/src/main/scala/docspell/joex/preview/AllPreviewsTask.scala
modules/joex/src/main/scala/docspell/joex/process/AttachmentPageCount.scala
modules/joex/src/main/scala/docspell/joex/process/ProcessItem.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/resources/db/migration/h2/V1.11.0__pdf_pages.sql
modules/store/src/main/resources/db/migration/mariadb/V1.11.0__pdf_pages.sql
modules/store/src/main/resources/db/migration/postgresql/V1.11.0__pdf_pages.sql
modules/store/src/main/scala/docspell/store/queries/QItem.scala
modules/store/src/main/scala/docspell/store/records/RAttachment.scala
modules/store/src/main/scala/docspell/store/records/RAttachmentMeta.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Data/UiSettings.elm
modules/webapp/src/main/elm/Page/Home/View.elm
modules/webapp/src/main/webjar/docspell.css

Pages metadata

---

modules/common/src/main/scala/docspell/common/ScanMailboxArgs.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala
modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm

Mail subject filter

---

modules/restapi/src/main/resources/docspell-openapi.yml
modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/Comp/FolderSelect.elm
modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/LinkTarget.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Comp/TagSelect.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/Home/Update.elm
modules/webapp/src/main/elm/Page/Home/View.elm
modules/webapp/src/main/elm/Page/ItemDetail/Data.elm
modules/webapp/src/main/elm/Page/ItemDetail/Update.elm
modules/webapp/src/main/elm/Util/Update.elm
modules/webapp/src/main/webjar/docspell.css

Quick links

---

modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
modules/common/src/main/scala/docspell/common/ScanMailboxArgs.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala
modules/webapp/src/main/elm/Comp/Dropzone.elm
modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
modules/webapp/src/main/elm/Page/Upload/Data.elm
modules/webapp/src/main/elm/Page/Upload/Update.elm
modules/webapp/src/main/elm/Page/Upload/View.elm

Language per request

---

modules/webapp/src/main/elm/Comp/CustomFieldInput.elm
modules/webapp/src/main/elm/Comp/CustomFieldMultiInput.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm

Allow to search with wildcard in a number custom field

---

tools/consumedir.sh

Consumedir fixes

---

modules/webapp/src/main/elm/App/Data.elm
modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/App/View.elm
modules/webapp/src/main/elm/Comp/DetailEdit.elm
modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/TagForm.elm
modules/webapp/src/main/elm/Comp/TagManage.elm
modules/webapp/src/main/elm/Data/Flags.elm
modules/webapp/src/main/elm/Page/CollectiveSettings/View.elm
modules/webapp/src/main/webjar/docspell.css

Also fixes a ui problem with a too long dropdown menu in the small
modal popup when adding tags or custom fields in item detail view.
Closes: #331 
Closes: #329

Allow to choose from existing tag categories

---

modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Comp/UiSettingsForm.elm
modules/webapp/src/main/elm/Data/ItemTemplate.elm
modules/webapp/src/main/elm/Data/UiSettings.elm
modules/webapp/src/main/elm/Util/List.elm

Card title

---

tools/export-files.sh
website/site/content/docs/faq/_index.md
website/site/content/docs/tools/export-files.md

Export files

---

modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Data/Fields.elm
modules/webapp/src/main/elm/Data/Icons.elm
modules/webapp/src/main/elm/Page/CollectiveSettings/View.elm

Source filter

---

modules/backend/src/main/scala/docspell/backend/ops/OOrganization.scala
modules/common/src/main/scala/docspell/common/PersonRef.scala
modules/joex/src/main/scala/docspell/joex/process/EvalProposals.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/resources/db/migration/h2/V1.14.0__person_org.sql
modules/store/src/main/resources/db/migration/mariadb/V1.14.0__person_org.sql
modules/store/src/main/resources/db/migration/postgresql/V1.14.0__person_org.sql
modules/store/src/main/scala/docspell/store/queries/QOrganization.scala
modules/store/src/main/scala/docspell/store/records/RPerson.scala
modules/webapp/src/main/elm/Comp/CustomFieldTable.elm
modules/webapp/src/main/elm/Comp/DetailEdit.elm
modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Comp/EquipmentTable.elm
modules/webapp/src/main/elm/Comp/FolderTable.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
modules/webapp/src/main/elm/Comp/OrgTable.elm
modules/webapp/src/main/elm/Comp/PersonForm.elm
modules/webapp/src/main/elm/Comp/PersonManage.elm
modules/webapp/src/main/elm/Comp/PersonTable.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Comp/TagTable.elm

Person org

---

modules/backend/src/main/scala/docspell/backend/auth/AuthToken.scala
modules/backend/src/main/scala/docspell/backend/auth/Login.scala
modules/backend/src/main/scala/docspell/backend/auth/RememberToken.scala
modules/backend/src/main/scala/docspell/backend/auth/TokenUtil.scala
modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/hk/CleanupRememberMeTask.scala
modules/joex/src/main/scala/docspell/joex/hk/HouseKeepingConfig.scala
modules/joex/src/main/scala/docspell/joex/hk/HouseKeepingTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/auth/CookieData.scala
modules/restserver/src/main/scala/docspell/restserver/auth/RememberCookieData.scala
modules/restserver/src/main/scala/docspell/restserver/routes/Authenticate.scala
modules/restserver/src/main/scala/docspell/restserver/routes/LoginRoutes.scala
modules/store/src/main/resources/db/migration/h2/V1.15.0__rememberme.sql
modules/store/src/main/resources/db/migration/mariadb/V1.15.0__rememberme.sql
modules/store/src/main/resources/db/migration/postgresql/V1.15.0__rememberme.sql
modules/store/src/main/scala/docspell/store/queries/QLogin.scala
modules/store/src/main/scala/docspell/store/records/RRememberMe.scala
modules/webapp/src/main/elm/Page/Login/Data.elm
modules/webapp/src/main/elm/Page/Login/Update.elm
modules/webapp/src/main/elm/Page/Login/View.elm

Remember me

---

build.sbt
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/ItemRoutes.scala
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Page/Home/Data.elm
modules/webapp/src/main/elm/Page/Home/Update.elm
modules/webapp/src/main/elm/Page/Home/View.elm
project/Dependencies.scala

Search improvements

---

modules/backend/src/main/scala/docspell/backend/ops/OItemSearch.scala
modules/joex/src/main/scala/docspell/joex/process/DuplicateCheck.scala
modules/joex/src/main/scala/docspell/joex/process/ItemHandler.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala

Fk on delete bug

---

modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm

Fix selecting imap connection in scan mailbox settings

---

modules/store/src/main/scala/docspell/store/queries/QItem.scala

The NOT-IN query must check for null separately, as everything with
null evaluates to false in sql resulting in not finding existing
duplicates.

Fixing find-by-checksum with exclusions

---

build.sbt
docker/docspell.conf
modules/backend/src/main/scala/docspell/backend/ops/OCollective.scala
modules/common/src/main/scala/docspell/common/Password.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/Config.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/http4s/QueryParam.scala
modules/restserver/src/main/scala/docspell/restserver/http4s/Responses.scala
modules/restserver/src/main/scala/docspell/restserver/routes/AdminRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/FullTextIndexRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/UserRoutes.scala
nix/module-server.nix
tools/export-files.sh
tools/reset-password/reset-password.sh
website/site/content/docs/api/intro.md
website/site/content/docs/configure/_index.md
website/site/content/docs/tools/reset-password.md

Password reset

---

build.sbt
modules/analysis/src/main/scala/docspell/analysis/TextAnalyser.scala
modules/analysis/src/main/scala/docspell/analysis/TextAnalysisConfig.scala
modules/analysis/src/main/scala/docspell/analysis/nlp/PipelineCache.scala
modules/analysis/src/main/scala/docspell/analysis/nlp/StanfordNerClassifier.scala
modules/common/src/main/scala/docspell/common/ByteSize.scala
modules/common/src/main/scala/docspell/common/JvmInfo.scala
modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/Config.scala
modules/joex/src/main/scala/docspell/joex/JoexServer.scala
modules/joex/src/main/scala/docspell/joex/routes/InfoRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/routes/InfoRoutes.scala
nix/module-joex.nix

Joex memory

---

modules/common/src/main/scala/docspell/common/Glob.scala
modules/common/src/test/scala/docspell/common/GlobTest.scala
modules/joex/src/main/scala/docspell/joex/mail/ReadMail.scala
modules/joex/src/main/scala/docspell/joex/process/ExtractArchive.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala

Scanmailbox fix

---

build.sbt
modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala

Date proposals

---

modules/analysis/src/main/scala/docspell/analysis/nlp/StanfordNerClassifier.scala
modules/store/src/main/scala/docspell/store/qb/DSL.scala
modules/store/src/main/scala/docspell/store/qb/Operator.scala
modules/store/src/main/scala/docspell/store/qb/impl/ConditionBuilder.scala
modules/store/src/main/scala/docspell/store/records/TagItemName.scala

Category search fix

---

modules/store/src/main/scala/docspell/store/queries/QOrganization.scala
modules/store/src/main/scala/docspell/store/records/RPerson.scala

Fix deleting organization

---

modules/common/src/main/scala/docspell/common/LenientUri.scala
modules/restserver/src/main/scala/docspell/restserver/webapp/Flags.scala

Render baseurl without trailing slash

---

modules/common/src/main/scala/docspell/common/ScanMailboxArgs.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala
modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
modules/webapp/src/main/elm/Comp/ScanMailboxManage.elm

Refactor scan mailbox form and add flag for post-processing

---

build.sbt
project/Dependencies.scala

Update emil to 0.7.1

---

modules/common/src/main/scala/docspell/common/IdRef.scala
modules/common/src/main/scala/docspell/common/Ident.scala
modules/common/src/main/scala/docspell/common/MetaProposal.scala
modules/common/src/main/scala/docspell/common/MetaProposalList.scala
modules/common/src/test/scala/docspell/common/MetaProposalListTest.scala
modules/joex/src/main/scala/docspell/joex/process/CrossCheckProposals.scala
modules/joex/src/main/scala/docspell/joex/process/EvalProposals.scala
modules/joex/src/main/scala/docspell/joex/process/ItemData.scala
modules/joex/src/main/scala/docspell/joex/process/LinkProposal.scala
modules/joex/src/main/scala/docspell/joex/process/ProcessItem.scala

Person suggestion fix

---

build.sbt
modules/common/src/main/scala/docspell/common/PersonUse.scala
modules/joex/src/main/scala/docspell/joex/process/FindProposal.scala
modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/resources/db/migration/h2/V1.20.0__personuse.sql
modules/store/src/main/resources/db/migration/mariadb/V1.20.0__personuse.sql
modules/store/src/main/resources/db/migration/postgresql/V1.20.0__personuse.sql
modules/store/src/main/scala/docspell/store/impl/DoobieMeta.scala
modules/store/src/main/scala/docspell/store/queries/QOrganization.scala
modules/store/src/main/scala/docspell/store/records/RPerson.scala
modules/webapp/src/main/elm/Comp/DateInput.elm
modules/webapp/src/main/elm/Comp/ItemDetail/MultiEditMenu.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/PersonForm.elm
modules/webapp/src/main/elm/Comp/PersonTable.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Data/PersonUse.elm

Allow person to be correspondent, concerning or both

---

modules/webapp/src/main/elm/Comp/ItemDetail/View2.elm
modules/webapp/src/main/elm/Data/ItemNav.elm
modules/webapp/src/main/elm/Page/Home/Data.elm

Show item position in detail view

---

modules/common/src/main/scala/docspell/common/Ident.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/resources/db/migration/h2/V1.20.1__equipment_description.sql
modules/store/src/main/resources/db/migration/h2/V1.20.2__org_shortname.sql
modules/store/src/main/resources/db/migration/mariadb/V1.20.1__equipment_description.sql
modules/store/src/main/resources/db/migration/mariadb/V1.20.2__org_shortname.sql
modules/store/src/main/resources/db/migration/postgresql/V1.20.1__equipment_description.sql
modules/store/src/main/resources/db/migration/postgresql/V1.20.2__org_shortname.sql
modules/store/src/main/scala/docspell/store/queries/QOrganization.scala
modules/store/src/main/scala/docspell/store/records/REquipment.scala
modules/store/src/main/scala/docspell/store/records/ROrganization.scala
modules/webapp/src/main/elm/Comp/EquipmentForm.elm
modules/webapp/src/main/elm/Comp/OrgForm.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm

Equipment description

---

modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/hk/CheckNodesTask.scala
modules/joex/src/main/scala/docspell/joex/hk/HouseKeepingConfig.scala
modules/joex/src/main/scala/docspell/joex/hk/HouseKeepingTask.scala
modules/store/src/main/resources/db/migration/h2/V1.20.3__node_seen.sql
modules/store/src/main/resources/db/migration/mariadb/V1.20.3__node_seen.sql
modules/store/src/main/resources/db/migration/postgresql/V1.20.3__node_seen.sql
modules/store/src/main/scala/docspell/store/records/RNode.scala
modules/webapp/src/main/elm/Comp/FolderSelect.elm
nix/module-joex.nix

Cleanup nodes

---

modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/resources/db/migration/h2/V1.20.4__source_lang.sql
modules/store/src/main/resources/db/migration/mariadb/V1.20.4__source_lang.sql
modules/store/src/main/resources/db/migration/postgresql/V1.20.4__source_lang.sql
modules/store/src/main/scala/docspell/store/records/RSource.scala
modules/webapp/src/main/elm/Comp/SourceForm.elm
modules/webapp/src/main/elm/Comp/SourceManage.elm

Allows to define upload urls for different languages.

Add language to a source

---

modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala

Allow more suggestions for date variants in English

---

docker/joex-base.dockerfile
modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala
modules/common/src/main/scala/docspell/common/Language.scala
modules/webapp/src/main/elm/Data/Language.elm

Add latvian language

---

modules/webapp/src/main/elm/Styles.elm
modules/webapp/src/main/styles/index.css

Add scrollbars

---

modules/query/shared/src/main/scala/docspell/query/internal/ExprUtil.scala
modules/store/src/test/scala/docspell/store/generator/ItemQueryGeneratorTest.scala

Fixes queries containing macros inside a "not".

Reduce not expressions

---

modules/webapp/src/main/elm/Comp/AttachmentMeta.elm
modules/webapp/src/main/elm/Comp/CalEventInput.elm
modules/webapp/src/main/elm/Comp/CustomFieldTable.elm
modules/webapp/src/main/elm/Comp/FolderTable.elm
modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Comp/ItemDetail/EditForm.elm
modules/webapp/src/main/elm/Comp/ItemDetail/ItemInfoHeader.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View2.elm
modules/webapp/src/main/elm/Comp/SentMails.elm
modules/webapp/src/main/elm/Comp/UserTable.elm
modules/webapp/src/main/elm/Data/ItemTemplate.elm
modules/webapp/src/main/elm/Messages/Comp/AttachmentMeta.elm
modules/webapp/src/main/elm/Messages/Comp/CalEventInput.elm
modules/webapp/src/main/elm/Messages/Comp/CustomFieldTable.elm
modules/webapp/src/main/elm/Messages/Comp/FolderTable.elm
modules/webapp/src/main/elm/Messages/Comp/ItemCard.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail/EditForm.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail/ItemInfoHeader.elm
modules/webapp/src/main/elm/Messages/Comp/SentMails.elm
modules/webapp/src/main/elm/Messages/Comp/UserTable.elm
modules/webapp/src/main/elm/Messages/Data/Direction.elm
modules/webapp/src/main/elm/Messages/DateFormat.elm
modules/webapp/src/main/elm/Messages/Page/Queue.elm
modules/webapp/src/main/elm/Page/Queue/View2.elm
modules/webapp/src/main/elm/Util/Time.elm

Prepare translating dates

---

modules/restapi/src/main/resources/docspell-openapi.yml
modules/store/src/main/scala/docspell/store/queries/CategoryCount.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala
modules/webapp/src/main/elm/Comp/TagSelect.elm

Fix query for getting tag categoy summary

---

modules/webapp/src/main/elm/Page/Upload/View2.elm

Remove upload meta form for anonymous uploads

---

modules/store/src/main/scala/docspell/store/qb/DSL.scala

Fix tag category search being case insensitive

---

modules/webapp/src/main/elm/Comp/TagManage.elm

The tag category is a bit special (sadly). The options are retrieved
by going through the tags. It must not update these, if a query
selects only a subset of tags.
Fixes: #880

Only update category options if the query selected all tags

---

tools/consumedir/consumedir.sh

Allows to control files to upload by either including or excluding
files via a shell glob pattern.
Closes: #885

Add include/exclude file filter for consumedir

---

modules/backend/src/main/scala/docspell/backend/JobFactory.scala

The id must be recreated for each job, obviously

---

modules/query/shared/src/main/scala/docspell/query/ItemQuery.scala
modules/query/shared/src/main/scala/docspell/query/internal/AttrParser.scala
modules/query/shared/src/main/scala/docspell/query/internal/Constants.scala
modules/query/shared/src/main/scala/docspell/query/internal/MacroParser.scala
modules/query/shared/src/test/scala/docspell/query/internal/SimpleExprParserTest.scala
modules/store/src/main/scala/docspell/store/qb/generator/ItemQueryGenerator.scala
website/site/content/docs/query/_index.md

Allow to use the created timestamp in item queries

---

modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Styles.elm

Left align item separator and make it more prominent

---

modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala

This is a follow up on #961. It was forgotten when the japanese
language was added.

Add the japanese content field to solr

---

docker/dockerfiles/joex.dockerfile
docker/dockerfiles/restserver.dockerfile

Fix health check in docker images

---

modules/restserver/src/main/scala/docspell/restserver/routes/AttachmentRoutes.scala

Fix path to viewerjs for pdf view

---

modules/webapp/src/main/elm/Comp/ItemDetail/FieldTabState.elm
modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Comp/Tabs.elm
modules/webapp/src/main/elm/Comp/UiSettingsForm.elm

Highlight search menu tabs that contain data

---

modules/webapp/src/main/elm/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/ShowQrCode.elm
modules/webapp/src/main/elm/Comp/ItemDetail/SingleAttachment.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemDetail/View2.elm
modules/webapp/src/main/elm/Comp/SourceManage.elm
modules/webapp/src/main/elm/Data/Icons.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail/SingleAttachment.elm
modules/webapp/src/main/elm/Page/ItemDetail/View2.elm
modules/webapp/src/main/elm/Ports.elm
modules/webapp/src/main/elm/Styles.elm
modules/webapp/src/main/webjar/docspell.js

Add a qr code to the link of an item or attachment

---

modules/backend/src/main/scala/docspell/backend/item/Merge.scala
modules/store/src/main/scala/docspell/store/records/RSentMailItem.scala

Move sent mails when merging items

---

project/Dependencies.scala

This pulls in a change to fix #1140

Update binny to 0.2.1

---

modules/backend/src/main/scala/docspell/backend/BackendApp.scala
modules/backend/src/main/scala/docspell/backend/msg/JobQueuePublish.scala
modules/backend/src/main/scala/docspell/backend/msg/JobSubmitted.scala
modules/backend/src/main/scala/docspell/backend/msg/Topics.scala
modules/backend/src/main/scala/docspell/backend/ops/OJob.scala
modules/joex/src/main/scala/docspell/joex/JoexAppImpl.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/Subscriptions.scala
modules/restserver/src/main/scala/docspell/restserver/ws/OutputEvent.scala
modules/restserver/src/main/scala/docspell/restserver/ws/WebSocketRoutes.scala
modules/store/src/main/scala/docspell/store/queue/JobQueue.scala
modules/store/src/main/scala/docspell/store/records/RJob.scala
modules/webapp/src/main/elm/App/Data.elm
modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/App/View2.elm
modules/webapp/src/main/elm/Data/ServerEvent.elm

Indicate number of running jobs in tob nav

---

modules/webapp/src/main/elm/App/Update.elm
modules/webapp/src/main/elm/App/View2.elm

Don't set the flag when already on "home page".

Fix notification about new items

---

modules/backend/src/main/scala/docspell/backend/BackendApp.scala
modules/backend/src/main/scala/docspell/backend/ops/OJob.scala

Publish event when a waiting job is removed

---

modules/webapp/src/main/elm/Comp/DueItemsTaskManage.elm
modules/webapp/src/main/elm/Comp/NotificationHookManage.elm
modules/webapp/src/main/elm/Comp/PeriodicQueryTaskForm.elm
modules/webapp/src/main/elm/Comp/PeriodicQueryTaskManage.elm

Fix deleting periodic query tasks

---

modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Page/Home/View2.elm

Fix preview css when switching between tile and list

---

modules/backend/src/main/scala/docspell/backend/ops/ONotification.scala
modules/notification/api/src/main/scala/docspell/notification/api/Channel.scala
modules/notification/api/src/main/scala/docspell/notification/api/NotificationChannel.scala
modules/notification/impl/src/main/scala/docspell/notification/impl/GotifyBackend.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restapi/src/main/scala/docspell/restapi/model/NotificationChannel.scala
modules/restapi/src/test/scala/docspell/restapi/model/NotificationCodecTest.scala
modules/store/src/main/resources/db/migration/h2/V1.31.1__gotify_prio.sql
modules/store/src/main/resources/db/migration/mariadb/V1.31.1__gotify_prio.sql
modules/store/src/main/resources/db/migration/postgresql/V1.31.1__gotify_prio.sql
modules/store/src/main/scala/docspell/store/queries/ChannelMap.scala
modules/store/src/main/scala/docspell/store/records/RNotificationChannelGotify.scala
modules/webapp/src/main/elm/Comp/IntField.elm
modules/webapp/src/main/elm/Comp/NotificationGotifyForm.elm
modules/webapp/src/main/elm/Messages/Comp/NotificationGotifyForm.elm

Add priority to gotify channel

---

modules/pubsub/naive/src/main/scala/docspell/pubsub/naive/NaivePubSub.scala
modules/store/src/main/scala/docspell/store/records/RPubSub.scala

Remove pubsub entries when shutting down and initialize by uri

---

modules/webapp/src/main/elm/Comp/Dropdown.elm
modules/webapp/src/main/elm/Util/Tag.elm

This is some low hanging fruit, related to #573, #960. At least we see
now the category and the filter is applied to it as well.

Improve selecting tags in the dropdown a bit

---

modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/DueItemsTaskForm.elm
modules/webapp/src/main/elm/Comp/ItemDetail/EditForm.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
modules/webapp/src/main/elm/Comp/ItemDetail/MultiEditMenu.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
modules/webapp/src/main/elm/Comp/SourceForm.elm
modules/webapp/src/main/elm/Comp/Tabs.elm
modules/webapp/src/main/elm/Comp/TagDropdown.elm
modules/webapp/src/main/elm/Data/Color.elm
modules/webapp/src/main/elm/Messages/Comp/DueItemsTaskForm.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail/EditForm.elm
modules/webapp/src/main/elm/Messages/Comp/ItemDetail/MultiEditMenu.elm
modules/webapp/src/main/elm/Messages/Comp/ScanMailboxForm.elm
modules/webapp/src/main/elm/Messages/Comp/SourceForm.elm
modules/webapp/src/main/elm/Messages/Comp/TagDropdown.elm
modules/webapp/src/main/elm/Util/Tag.elm

Tag cat select

---

modules/restserver/src/main/scala/docspell/restserver/routes/CollectiveRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/NotifyDueItemsRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/PeriodicQueryRoutes.scala
modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala

Reordered some routes due to a change in http4s

---

modules/joex/src/main/scala/docspell/joex/notify/PeriodicQueryTask.scala

It didn't specify to only search in valid items
Fixes: #1323

Fix query in periodic query task

---

modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/tailwind.config.js

Add more breakpoints and increase card column count

---

modules/joex/src/main/resources/reference.conf
modules/logging/scribe/src/main/scala/docspell/logging/impl/ScribeConfigure.scala
modules/restserver/src/main/resources/reference.conf
modules/webapp/src/main/elm/Comp/BoxQueryView.elm
modules/webapp/src/main/elm/Comp/ItemColumnView.elm
nix/module-joex.nix
nix/module-server.nix
project/TestSettings.scala

Dashboard tables

---

modules/webapp/src/main/elm/Comp/TagSelect.elm

Filter out empty tag categories in search menu

---

.github/workflows/release-nightly.yml
.github/workflows/release.yml
build.sbt
tools/README.md
tools/start-local/README.md
tools/start-local/start-local.sh
tools/webextension/README.md

It doesn't contain anything generally useful anymore.

Remove tools from a release

---

docker/dockerfiles/build.sh
docker/dockerfiles/joex.dockerfile
docker/dockerfiles/restserver.dockerfile

Docker on arm

---

modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/PeriodicSchedulerImpl.scala
project/Dependencies.scala

Use calev-fs2 artifact

---

modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/Config.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/restserver/src/main/scala/docspell/restserver/routes/UploadRoutes.scala
nix/module-server.nix

Fix large file upload

---

modules/backend/src/main/scala/docspell/backend/ops/OItemSearch.scala
modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
modules/store/src/main/scala/docspell/store/queries/ItemData.scala
modules/store/src/main/scala/docspell/store/queries/ListItemWithTags.scala
modules/store/src/main/scala/docspell/store/queries/QItem.scala
modules/webapp/src/main/elm/Comp/ItemCard.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
modules/webapp/src/main/elm/Comp/ItemLinkForm.elm
modules/webapp/src/main/elm/Comp/LinkTarget.elm
modules/webapp/src/main/elm/Comp/SearchMenu.elm
modules/webapp/src/main/elm/Messages/Comp/ItemCard.elm
modules/webapp/src/main/elm/Util/Item.elm

- Quickly select related items from the search view
- Include related items with item details to spare another request

Select linked items from search page

---

.github/workflows/ci.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml

The cache value seems to be corrupted:
> Decoding error (36) : Restored data doesn't match checksum

Change cache-key, to force create a new value

---

modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/PeriodicTaskStore.scala
modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/QUserTask.scala
modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/UserTaskStoreImpl.scala
modules/store/src/main/scala/docspell/store/records/RPeriodicTask.scala

Avoid logging non-errors as error

---

docker/docker-compose/docker-compose.yml

Some more common settings are added to apply changes more
conveniently.
Refs: #1530
Refs: #1551

Add more default docker settings

---

modules/backend/src/main/scala/docspell/backend/Config.scala
modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/Config.scala
modules/joex/src/main/scala/docspell/joex/JoexServer.scala
modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
modules/store/src/main/scala/docspell/store/SchemaMigrateConfig.scala
modules/store/src/main/scala/docspell/store/Store.scala
modules/store/src/main/scala/docspell/store/impl/StoreImpl.scala
modules/store/src/main/scala/docspell/store/migrate/FlywayMigrate.scala
modules/store/src/test/scala/docspell/store/StoreFixture.scala
modules/store/src/test/scala/docspell/store/migrate/H2MigrateTest.scala
modules/store/src/test/scala/docspell/store/migrate/MariaDbMigrateTest.scala
modules/store/src/test/scala/docspell/store/migrate/PostgresqlMigrateTest.scala

Configure run/repair db migrations

---

modules/addonlib/src/main/scala/docspell/addons/out/AddonOutput.scala
modules/backend/src/main/scala/docspell/backend/joex/AddonPostProcess.scala
modules/backend/src/main/scala/docspell/backend/ops/OAddons.scala

- Fix applying new-items from addon results
- Notify joex when a scheduled addon is updated

Fixes related to addons

---

modules/store/src/test/scala/docspell/store/DatabaseTest.scala
modules/webapp/src/main/elm/Comp/ItemCardList.elm
modules/webapp/src/main/elm/Messages/Page/Share.elm
modules/webapp/src/main/elm/Page/Share/Data.elm
modules/webapp/src/main/elm/Page/Share/LoadMore.elm
modules/webapp/src/main/elm/Page/Share/Menubar.elm
modules/webapp/src/main/elm/Page/Share/Update.elm
modules/webapp/src/main/elm/Page/Share/View.elm

Add paging to share view

---

modules/oidc/src/main/scala/docspell/oidc/CodeFlowRoutes.scala

Should fix #1619 - Cannot compile offline to test. I am not familiar with SBT.

Add state to oidc uri

---

modules/analysis/src/main/scala/docspell/analysis/contact/Contact.scala
modules/backend/src/main/scala/docspell/backend/auth/TokenUtil.scala
modules/backend/src/main/scala/docspell/backend/signup/OSignup.scala
modules/common/src/main/scala/docspell/common/LenientUri.scala
modules/common/src/main/scala/docspell/common/UrlMatcher.scala
modules/common/src/main/scala/docspell/common/util/SignUtil.scala
modules/common/src/test/scala/docspell/common/LenientUriTest.scala
modules/common/src/test/scala/docspell/common/util/SignUtilTest.scala
modules/oidc/src/main/scala/docspell/oidc/CodeFlow.scala
modules/oidc/src/main/scala/docspell/oidc/CodeFlowConfig.scala
modules/oidc/src/main/scala/docspell/oidc/CodeFlowRoutes.scala
modules/oidc/src/main/scala/docspell/oidc/StateParam.scala
modules/oidc/src/test/scala/docspell/oidc/StateParamTest.scala
modules/restserver/src/main/scala/docspell/restserver/auth/OpenId.scala
modules/store/src/main/scala/docspell/store/file/FileUrlReader.scala

OIDC improvements

---

modules/extract/src/main/scala/docspell/extract/PdfExtract.scala
modules/joex/src/main/resources/reference.conf

Allow to always use OCR extracted text

---

docker/dockerfiles/build.sh

See PR #1713, if support is wanted, please open an issue or better a
PR ;-).

Drop armv7 support for docker images

---

website/site/content/docs/install/download_run.md
website/site/templates/shortcodes/deb_files.html
website/site/templates/shortcodes/zip_files.html
website/yarn.lock

Upgrade website packages and fix download links

---

modules/restapi/src/main/resources/docspell-openapi.yml
modules/restserver/src/main/scala/docspell/restserver/routes/AttachmentRoutes.scala
modules/webapp/src/main/elm/Api.elm
modules/webapp/src/main/elm/Comp/AttachmentMeta.elm
modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm

Allow to change extracted text of attachments

---

modules/webapp/src/main/elm/Data/ItemQuery.elm

Fix query generated for linked queries

---

docker/dockerfiles/joex.dockerfile
modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindTest.scala
modules/common/src/main/scala/docspell/common/Language.scala
modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala
modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala
modules/webapp/src/main/elm/Data/Language.elm
modules/webapp/src/main/elm/Messages/Data/Language.elm

Add Estonian language

---

modules/webapp/src/main/elm/Comp/ItemMerge.elm
modules/webapp/src/main/elm/Data/ItemIds.elm
modules/webapp/src/main/elm/Page/Search/Update.elm

Fix item selection after merge

---

modules/common/src/main/scala/docspell/common/syntax/StringSyntax.scala
modules/restserver/src/main/scala/docspell/restserver/routes/ShareRoutes.scala

Fix querying shares without a name

---

modules/webapp/src/main/elm/Comp/CustomFieldInput.elm
modules/webapp/src/main/elm/Comp/ItemSearchInput.elm
modules/webapp/src/main/elm/Comp/SimpleTextInput.elm

Map comma to dot for numeric custom fields

---

.gitignore
modules/joex/src/main/scala/docspell/joex/JoexServer.scala
modules/joex/src/main/scala/docspell/joex/hk/CheckNodesTask.scala
modules/joexapi/src/main/scala/docspell/joexapi/client/JoexClient.scala
modules/notification/api/src/main/scala/docspell/notification/api/Channel.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
project/Dependencies.scala

This fixes  #2221. The issue is marked complex so I am not sure if I missed something so please provide feedback.

Replace `http4s-blaze-client` with `http4s-ember-client`.

---

.github/workflows/ci.yml
build.sbt
modules/addonlib/src/main/scala/docspell/addons/AddonMeta.scala
modules/convert/src/main/scala/docspell/convert/RemovePdfEncryption.scala
modules/convert/src/test/scala/docspell/convert/FileChecks.scala
modules/extract/src/main/scala/docspell/extract/pdfbox/PdfLoader.scala
modules/extract/src/main/scala/docspell/extract/pdfbox/PdfboxExtract.scala
modules/extract/src/test/scala/docspell/extract/pdfbox/PdfboxExtractTest.scala
modules/logging/scribe/src/main/scala/docspell/logging/impl/Record.scala
modules/logging/scribe/src/main/scala/docspell/logging/impl/ScribeWrapper.scala
modules/oidc/src/main/scala/docspell/oidc/SignatureAlgo.scala
modules/store/src/main/scala/docspell/store/Store.scala
modules/store/src/main/scala/docspell/store/file/BinnyUtils.scala
modules/store/src/main/scala/docspell/store/file/FileRepository.scala
modules/store/src/main/scala/docspell/store/impl/StoreImpl.scala
nix/checks/configuration-test.nix
nix/flake.nix
project/Dependencies.scala
project/build.nix
website/site/content/docs/install/prereq.md

Updates several dependencies, requires now JDK17+

Build updates

---

docker/dockerfiles/joex.dockerfile

And hope the ocrmypdf installed via apk is working now.

Remove pip3 install

---

modules/common/src/main/scala/docspell/common/util/ResourceUse.scala
modules/joex/src/main/scala/docspell/joex/JoexServer.scala
modules/restserver/src/main/scala/docspell/restserver/RestServer.scala

Fix http server startup

---

modules/common/src/main/scala/docspell/common/Binary.scala
modules/common/src/main/scala/docspell/common/util/ResourceUse.scala
modules/convert/src/main/scala/docspell/convert/flexmark/Markdown.scala
modules/joex/src/main/scala/docspell/joex/JoexServer.scala

The code removed here was copied from another project some years back. Now there is an improved version in fs2 that can be used.
Fixes: #2376

Fix potential infinite loop

---

website/site/content/docs/addons/writing.md
website/src/main/scala/docspell/website/AddonOutputExample.scala

Document the new `set-date` addon action introduced by #2362.

Add documentation for #2362

---

.github/workflows/ci-docs.yml
.github/workflows/website.yml
website/shell.nix
website/yarn.lock

Update website build

---

modules/backend/src/main/scala/docspell/backend/Config.scala
modules/common/src/main/scala/docspell/common/FileStoreConfig.scala
modules/joex/src/main/resources/reference.conf
modules/joex/src/main/scala/docspell/joex/ConfigFile.scala
modules/restserver/src/main/resources/reference.conf
modules/restserver/src/main/scala/docspell/restserver/ConfigFile.scala
modules/store/src/main/scala/docspell/store/file/BinnyUtils.scala
modules/store/src/main/scala/docspell/store/file/FileRepositoryConfig.scala
website/site/content/docs/configure/file-backends.md
website/site/content/docs/tools/cli.md

Allow to configure a region for s3 backend

---

docker/dockerfiles/joex.dockerfile
modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
modules/analysis/src/test/scala/docspell/analysis/date/DateFindTest.scala
modules/common/src/main/scala/docspell/common/Language.scala
modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala
modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala
modules/webapp/src/main/elm/Data/Language.elm
modules/webapp/src/main/elm/Messages/Data/Language.elm

Just the basic support was added following examples for other languages. Apologies in advance for any errors, I'm very unfamiliar with Scala/Elm.

Add support for Slovak language

---

modules/restserver/src/main/scala/docspell/restserver/ConfigFile.scala

Validate config for session-valid

---

modules/joex/src/main/scala/docspell/joex/multiupload/MultiUploadArchiveTask.scala
website/site/content/docs/api/upload.md

Apply `flattenArchives` to email files

---

modules/webapp/src/main/elm/Comp/UploadForm.elm

Allow select files without clicking reset

---

kubernetes/README.md
kubernetes/ingress.yaml
kubernetes/postgres.yaml
kubernetes/solr.yaml

Fixing Kustomize issues described in #2498

Fix some Kubernetes Kustomize deployment issues

---

website/site/content/docs/install/download_run.md

Fixes a typo in PostgreSQL manual instructions.

Pushing a minor fix to the bash commands.

---

website/site/content/docs/dev/development.md

docs(development.md): Fix minor typos

---

nix/modules/server.nix

Add logout-url option to Nix module

---

modules/addonlib/src/main/scala/docspell/addons/runner/RunnerUtil.scala
modules/addonlib/src/test/scala/docspell/addons/AddonMetaTest.scala

Honor default value `true` for `collectOutput`

---

modules/fts-solr/src/main/scala/docspell/ftssolr/Field.scala
modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala

This is a fixup for the jpn_vert addition to make the solr queries work.

Use japanese language for jpn_vert for solr
