- build.sbt
- modules/backend/src/main/scala/docspell/backend/ops/OJob.scala
- modules/backend/src/main/scala/docspell/backend/ops/OJoex.scala
- modules/common/src/main/scala/docspell/common/JobState.scala
- modules/joex/src/main/scala/docspell/joex/process/ItemHandler.scala
- modules/joex/src/main/scala/docspell/joex/process/ProcessItem.scala
- modules/joex/src/main/scala/docspell/joex/scheduler/SchedulerImpl.scala
- modules/joexapi/src/main/scala/docspell/joexapi/client/JoexClient.scala
- modules/microsite/docs/doc/processing.md
- modules/store/src/main/scala/docspell/store/queries/QItem.scala
- modules/store/src/main/scala/docspell/store/records/RJob.scala
A request to cancel a job was not processed correctly. The cancelling
routine of a task must run, regardless of the (non-final) state. Now
it works like this: if a job is currently running, it is interrupted
and its cancel routine is invoked. It then enters "cancelled" state.
If it is stuck, it is loaded and only its cancel routine is run. If it
is in a final state or waiting, it is removed from the queue.
> Fix cancelling jobs

- docker/joex.dockerfile
- modules/convert/src/main/scala/docspell/convert/Conversion.scala
- modules/convert/src/main/scala/docspell/convert/ConvertConfig.scala
- modules/convert/src/main/scala/docspell/convert/extern/ExternConv.scala
- modules/convert/src/main/scala/docspell/convert/extern/OcrMyPdf.scala
- modules/convert/src/main/scala/docspell/convert/extern/OcrMyPdfConfig.scala
- modules/convert/src/test/scala/docspell/convert/ConversionTest.scala
- modules/joex/src/main/resources/reference.conf
- modules/joex/src/main/scala/docspell/joex/process/ConvertPdf.scala
- modules/joex/src/main/scala/docspell/joex/process/TextExtraction.scala
- modules/microsite/docs/dev/adr.md
- modules/microsite/docs/dev/adr/0015_convert_pdf_files.md
- modules/microsite/docs/doc/install.md
- modules/microsite/docs/features.md
- modules/store/src/main/scala/docspell/store/records/RFileMeta.scala
- nix/module-joex.nix
- Use another external tool to convert pdf to pdf which also adds the
extracted text as another layer into the pdf
- Although not used, the external conversion routine will now check
for an existing text file that is named as the pdf file with extension
`.txt`. If present it is included in the conversion result and will be
used as the extracted text.
- text extraction for pdf files happens now on the converted file,
because it may already contain the text from the conversion step and
thus avoids running OCR twice.
- All errors during conversion are not fatal; processing continues
without a converted file.
> Use ocrmypdf tool to create pdf/a during conversion

- modules/webapp/src/main/elm/Comp/ItemDetail.elm
- modules/webapp/src/main/webjar/docspell.css
Either the width and appearance must be changed to match this of an
`ui action input` or the position must be fixed as done here. It is
not correctly positioned, because the `ui input` class uses a flex.
See #186
> Fix datepicker position for action input fields

- modules/webapp/src/main/elm/Page/CollectiveSettings/View.elm
It was displayed in some random order. Now the most used tag is first.
> Sort tag list by count

- modules/webapp/src/main/elm/Comp/CalEventInput.elm
- modules/webapp/src/main/elm/Comp/NotificationForm.elm
- modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
The problem was that the field executes a request to validate its
state. This was initiated at the same time for two values. Then it was
undetermined which value comes back first.
> Fixes a race condition when initializing the calendar-event field

- modules/store/src/main/resources/db/migration/h2/V1.9.3__joblog_counter.sql
- modules/store/src/main/resources/db/migration/mariadb/V1.9.3__joblog_counter.sql
- modules/store/src/main/resources/db/migration/postgresql/V1.9.3__joblog_counter.sql
- modules/store/src/main/scala/docspell/store/records/RJobLog.scala
This is to distinguish log entries created at the same time.
> Add counter to joblog for correct log order

- modules/restapi/src/main/resources/docspell-openapi.yml
- The `itemId` parameter was not declared for
`item/{itemId}/reprocess`
- `tagCategories*` must be declared required for `ItemSearch`
structure
Fixes #338
> Fix openapi spec for rest-server

- build.sbt
Default database is H2 which requires that both processes can access
the file.
Fixes #336
> debian packages: use same system user

- tools/import-paperless/import-paperless.sh
allows to import files, tags and correspondents (as organization) from [Paperless](https://github.com/the-paperless-project/paperless/) (fixes #358)
Parameters are 
* `ds_url`: Base-url of docspell
* `ds_user`: Username, possibly incl. collective 
* `ds_password`: Password
* `db_path`: Path to SQLite file of Paperless
Should be mapped to `/usr/src/paperless/data/db.sqlite3` when using Paperless with docker
* `file_path`: Path to base-path of Paperless' files
Should be mapped to `/usr/src/paperless/media/documents/originals/` when using Paperless with docker
> paperless importer (#358)

- modules/joex/src/main/scala/docspell/joex/analysis/NerFile.scala
- modules/joex/src/main/scala/docspell/joex/process/FindProposal.scala
- modules/joex/src/test/scala/docspell/joex/analysis/NerFileTest.scala
Patterns are split on whitespace by the nlp library and then compiled,
so each "word" must be a valid regex.
Fixes: #356
> Fix regex patterns used for NER

- tools/import-paperless/README.md
- tools/import-paperless/import-paperless.sh
* errors, specially during long initial runs are caught better now and should continue, if possible
* set `SKIP_EXISTING_DOCS` to `true` (default) to skip existing documents (if set to false, they won't be uploaded again, but tags, correspondent, date and title will be overwritten)
* for testing purposes you can set the variables `LIMIT` and `LIMIT_DOC` to limit the tags and correspondents respectively the documents and document-tag-relations
link #358
> paperless-importer (v0.3 beta) - added SKIP_EXISTING_DOCS variable and improved error handling

- docker/joex-entrypoint.sh
- docker/joex-ocrmypdf.sh
- docker/joex.dockerfile
- if `/var/run/docker.sock` is found in the docker-container, this feature is activated - if not, nothing changes
- usage:
- mount bind `docker.sock` from host by using `-v` or `volumes:`
- set environment variable when a certain version of the used docker image is preferred: `OCRMYPDF_VERSION=v11.3.0` or `OCRMYPDF_VERSION=latest`, default (if not set) is `v11.2.1`
addresses #387
> (DOCKER) allows to use jbarlow83's official docker image of OCRmyPDF, i.e. use a newer version

- modules/webapp/src/main/elm/Data/Items.elm
When replacing changed cards the fulltext highlighting should be
preserved from the original item.
Issue: #253
> Preserve context highlighting from full-text search

- docker/base.dockerfile
Now the timezone can be set as expected using TZ env variable (has already been set in default `.env` file).
Leads to proper log times (and of course everything else time related as well)
replaces #394
> (Docker) fixed wrong timezone because of missing tzdata package

- modules/store/src/main/scala/docspell/store/queries/QItem.scala
MariaDB below 10.4 doesn't support parentheses around selects for
`intersect` and `union`.
https://mariadb.com/kb/en/intersect/#parentheses
Fixes #404
> Fix sql error for mariadb <10.4

- modules/restserver/src/main/scala/docspell/restserver/webapp/TemplateRoutes.scala
- modules/webapp/src/main/elm/App/View.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/View.elm
- modules/webapp/src/main/elm/Comp/Progress.elm
- modules/webapp/src/main/elm/Page/Queue/Update.elm
- modules/webapp/src/main/elm/Page/Queue/View.elm
- modules/webapp/src/main/elm/Page/Upload/Data.elm
- modules/webapp/src/main/elm/Page/Upload/Update.elm
- modules/webapp/src/main/elm/Page/Upload/View.elm
- modules/webapp/src/main/elm/Ports.elm
- modules/webapp/src/main/webjar/docspell.js
- project/Dependencies.scala
Replaced semantic-ui with the drop-in replacement fomantic-ui [0]
which is a maintained fork. The fomantic-ui used here is a custom
build [1] of the less-version _without_ google-fonts (css-only). The
javascript part of fomantic-ui is not used, and also jquery could be
dropped now.
[0] https://fomantic-ui.com
[1] https://github.com/eikek/fomantic-slim-default
Closes: #349
> Introduce fomantic-ui, replacing semantic-ui

- build.sbt
Due to hardcoding files, the new ones were not packaged.
> Fix packaging tools

- tools/consumedir.sh
A collective can disable the endpoint at any time. So informing about
a misconfigured or disabled endpoint on start for each known
collective.
Closes #470
> Log a warning if the setup check fails

- modules/webapp/src/main/elm/Comp/ItemDetail/EditMenu.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
- modules/webapp/src/main/elm/Comp/SearchMenu.elm
Now a person that is not marked as "concerning only" is treated as
"correspondent only". The options of all dropdown fields are now
restricted to those subsets.
Closes: #332
> Show concerning/correspond person exclusively in dropdowns

- modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
Due to an off-by-one issue, dates in January could not be detected. This PR aims at fixing this. Since January is at index 0, the filter needs to check for > -1 (or >= 0).
> DateFind could not handle dates in January

- docker/docker-compose.yml
- docker/docspell.conf
Container name can't be hard coded and each joex instance needs a unique
name. Since Docker always sets the `HOSTNAME` variable and these are
unique, we can just interpolate the hostname into the joex app
identifier, to avoid creating multiple config files.
> Allow scaling joex with `docker-compose up --scale`

- docker/base-binaries.dockerfile
Due to the shell files being moved in the subdirectories, the `chmod` no longer applies to them. This will result in the `consumedir` container failing, as the entry point is not executable.
This pull request fixes this issue.
Include shell files in subdirectory of `/opt/docspell-tools/` via `**/*.sh`.
As there is no CLA here: Code released under the original license or any other license chosen for the repo now and/or in the future.
> Fix permission of scripts in base-binaries

- docker/consumedir-entrypoint.sh
I just noticed that CONSUMEDIR_DELETE  wasn't handled yet. This fixes it.
> Fix CONSUMEDIR_DELETE being ignored

- docker/docker-compose.yml
- docker/docspell.conf
Reverts https://github.com/eikek/docspell/pull/552 to use a simpler
setup. Leave instructions to get back the more advanced setup provided
by PR #522. Also, #617 has more contextual info.
Fixes: #608
Closes: #617
> Docker: revert PR #522, use one single joex instance

- modules/common/src/main/scala/docspell/common/LenientUri.scala
- modules/common/src/test/scala/docspell/common/LenientUriTest.scala
The read routine did not report all errors in the return type but some
raised exceptions.
> Fix reading uri from a string

- website/site/content/docs/webapp/scanmailbox.md
On imap, the separator between (sub)folders is not a slash, but a dot - at least on Dovecot. Took me some time to figure out, so I thought I leave a comment in the documentation :slightly_smiling_face:
> Documentation: imap folder separator may be a dot

- docker/dev-build-images.sh
- docker/dev-push-images.sh
- docker/hooks/build
The docker bash scripts try to get the version from sbt, without
calling sbt but reading the files. This was relying on a specific
position. It is now a bit more robust.
> Make detecting version more reliable

- tools/consumedir-cleaner/consumedir-cleaner.sh
Since `bc` isn't available for Windows I changed it to use `expr`.
> Make consumedir-cleaner able to run on Windows

- tools/download-files/download-files.sh
- tools/export-files/export-files.sh
It seems that older jq versions choke on some output from curl inside
these scripts. But I couldn't reproduce this on the cmdline; so not
really sure what's going on, suspecting some settings in the bash
script. Tested this with jq-1.5 and jq-1.6, both worked. But since
`xargs` also trims a string from quotes and whitespace, it can be used
instead of jq in these places.
> Don't use jq to clean whitespace/quotes

- modules/webapp/src/main/elm/Comp/Dropdown.elm
Closing the dropdown menu is now possible with ESC. Space will only
open the dropdown, but not close it. So now it's possible to type a
space into the search field.
Fixes: #863
> Don't toggle dropdown on space

- modules/webapp/src/main/elm/Comp/SourceForm.elm
When receiving a new value to display in the form, the language
dropdown was not initialized with the corresponding value.
Fixes: #877
> Update language dropdown for new data

- Changelog.md
- modules/backend/src/main/scala/docspell/backend/ops/OItem.scala
- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/AttachmentRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/CollectiveRoutes.scala
- tools/preview/regenerate-previews.sh
- website/site/content/docs/tools/regenerate-previews.md
It doesn't make much sense to have this per collective, because this
is triggered by an admin after changing the server config file. So it
is now implemented as an admin endpoint that affects all files.
> Replace generating preview images with an admin endpoint

- build.sbt
Since scala also produces class files version 52, the few java files
should also be compiled into this format.
> Compile the small number of java source files to java 8 target

- modules/webapp/src/main/elm/App/Update.elm
- modules/webapp/src/main/elm/Comp/ItemCardList.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Model.elm
- modules/webapp/src/main/elm/Comp/ItemDetail/Update.elm
- modules/webapp/src/main/elm/Page/Home/Data.elm
- modules/webapp/src/main/elm/Page/Home/Update.elm
- modules/webapp/src/main/elm/Page/ItemDetail/Data.elm
- modules/webapp/src/main/elm/Page/ItemDetail/Update.elm
When an item is deleted in detail view, the results must be updated to
reflect the new state. The results are now changed by removing the
corresponding item.
Fixes: #920
> Remove a deleted item from search results

- docker/dockerfiles/joex.dockerfile
- modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
- modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
- modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala
- modules/common/src/main/scala/docspell/common/Language.scala
- modules/webapp/src/main/elm/Data/Language.elm
- modules/webapp/src/main/elm/Messages/Data/Language.elm
Hi @wallace11 
this is my take … you can look at `DateFindSpec` if the tests make any sense. At least now tesseract is called with `-l jpn`
Closes: #948
> Add japanese document language

- modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
- modules/analysis/src/test/scala/docspell/analysis/date/DateFindSpec.scala
Hi there,
Here's some more sensible Japanese tests.
I hope that they pass 😆
> Japanese test improvements

- docker/dockerfiles/joex.dockerfile
They seem to work better as suggested here:
https://github.com/tesseract-ocr/tessdata/issues/119
Refs: #973
> Use different japanese train files for tesseract

- build.sbt
- modules/backend/src/main/scala/docspell/backend/ops/OCollective.scala
- modules/backend/src/main/scala/docspell/backend/ops/OItemSearch.scala
- modules/backend/src/main/scala/docspell/backend/ops/OUserTask.scala
- modules/common/src/main/scala/docspell/common/EmptyTrashArgs.scala
- modules/joex/src/main/scala/docspell/joex/JoexAppImpl.scala
- modules/joex/src/main/scala/docspell/joex/emptytrash/EmptyTrashTask.scala
- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/routes/CollectiveRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/NotifyDueItemsRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala
- modules/store/src/main/resources/db/migration/h2/V1.25.2__add_trash_min_age.sql
- modules/store/src/main/resources/db/migration/mariadb/V1.25.2__add_trash_min_age.sql
- modules/store/src/main/resources/db/migration/postgresql/V1.25.2__add_trash_min_age.sql
- modules/store/src/main/scala/docspell/store/impl/DoobieMeta.scala
- modules/store/src/main/scala/docspell/store/queries/QUserTask.scala
- modules/store/src/main/scala/docspell/store/records/RCollective.scala
- modules/store/src/main/scala/docspell/store/records/REmptyTrashSetting.scala
- modules/store/src/main/scala/docspell/store/records/RItem.scala
- modules/store/src/main/scala/docspell/store/usertask/UserTask.scala
- modules/store/src/main/scala/docspell/store/usertask/UserTaskStore.scala
- modules/webapp/src/main/elm/Api.elm
- modules/webapp/src/main/elm/Comp/CollectiveSettingsForm.elm
- modules/webapp/src/main/elm/Comp/EmptyTrashForm.elm
- modules/webapp/src/main/elm/Comp/IntField.elm
- modules/webapp/src/main/elm/Messages/Comp/CollectiveSettingsForm.elm
- modules/webapp/src/main/elm/Messages/Comp/EmptyTrashForm.elm
- modules/webapp/src/main/elm/Page/Home/View2.elm
In order to keep deleted items for a while, the periodic task can now
use a duration to only remove items with a certain age. This can be
used to ensure that a deleted item stays at least X days before it
will be removed from the database.
Refs: #347
> Use a minimum age of items to remove

- modules/backend/src/main/scala/docspell/backend/BackendApp.scala
- modules/backend/src/main/scala/docspell/backend/fulltext/CreateIndex.scala
- modules/backend/src/main/scala/docspell/backend/ops/OItem.scala
- modules/backend/src/main/scala/docspell/backend/ops/OSimpleSearch.scala
- modules/fts-client/src/main/scala/docspell/ftsclient/TextData.scala
- modules/joex/src/main/scala/docspell/joex/JoexAppImpl.scala
- modules/joex/src/main/scala/docspell/joex/fts/FtsContext.scala
- modules/joex/src/main/scala/docspell/joex/fts/FtsWork.scala
- modules/joex/src/main/scala/docspell/joex/fts/Migration.scala
- modules/joex/src/main/scala/docspell/joex/fts/MigrationTask.scala
- modules/joex/src/main/scala/docspell/joex/fts/ReIndexTask.scala
- modules/store/src/main/scala/docspell/store/queries/QAttachment.scala
- modules/store/src/main/scala/docspell/store/queries/QItem.scala
First, when checking for existence of a file, deleted items are not
conisdered.
The working with fulltext search has been changed: deleted items are
removed from fulltext index and are re-added when they are restored.
The fulltext index currently doesn't hold the item state and it would
mean much more work to introduce it into the index (or, worse, to
reprocess the results from the index). Thus, deleted items can only be
searched using database queries. It is probably a very rare use case
when fulltext search should be applied to deleted items. They have
been deleted for a reason and the most likely case is that they are
simply removed.
Refs: #347
> Fixup for deleting items

- modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
- modules/store/src/main/resources/db/migration/h2/V1.25.4__add_source_attachonly.sql
- modules/store/src/main/resources/db/migration/mariadb/V1.25.4__add_source_attachonly.sql
- modules/store/src/main/resources/db/migration/postgresql/V1.25.4__add_source_attachonly.sql
- modules/store/src/main/scala/docspell/store/records/RSource.scala
- modules/webapp/src/main/elm/Comp/SourceForm.elm
- modules/webapp/src/main/elm/Messages/Comp/SourceForm.elm
The upload request can now contain a boolean for importing only
attachments when e-mails are uploaded. This option is now also added
to a source url.
Refs: #983
> Add the attachment-only option to a source

- docker/dockerfiles/joex.dockerfile
- modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
- modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
- modules/common/src/main/scala/docspell/common/Language.scala
- modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala
- modules/webapp/src/main/elm/Data/Language.elm
- modules/webapp/src/main/elm/Messages/Data/Language.elm
Bet you didn't see that one coming ;)
I basically monkey-patched this based off #961 and #968.
The result was never executed, but I made sure to carefully check each change.
I didn't find it necessary to add any test because the other tests pretty much cover everything already.
Cheers.
> Add hebrew document language

- build.sbt
The start scripts contain a huge command that may cause problems on
some systems, reportedly at windows. The ClasspathJarPlugin can
mitigate this by creating a tiny jar that only contains the classpath
of the app.
https://sbt-native-packager.readthedocs.io/en/stable/recipes/longclasspath.html#generate-a-classpath-jar
> Reduce startup command length

- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
- modules/restserver/src/main/scala/docspell/restserver/http4s/ContentDisposition.scala
- modules/restserver/src/test/scala/docspell/restserver/http4s/ContentDispositionTest.scala
This adds a modified parser for `Content-Disposition` header to fix
issue #991. The parser in http4s for `Content-Disposition` header
removes filenames that are sent as plain utf8 bytes. See also
http4s/http4s#5053.
Closes: #991
> Fix uploads with utf8 bytes in filenames

- modules/store/src/test/scala/docspell/store/migrate/MariaDbMigrateTest.scala
- modules/store/src/test/scala/docspell/store/migrate/PostgresqlMigrateTest.scala
They were disabled due to network problems
> Enable tests again

- modules/backend/src/main/scala/docspell/backend/ops/ONotification.scala
- modules/joex/src/main/scala/docspell/joex/notify/PeriodicDueItemsTask.scala
- modules/joex/src/main/scala/docspell/joex/notify/PeriodicQueryTask.scala
- modules/joex/src/main/scala/docspell/joex/notify/TaskOperations.scala
When looking up the mail settings, a valid user id must be given.
Fixes: #1229
> Fix sending notification mails from background tasks

- modules/webapp/src/main/elm/Page/Home/View2.elm
When fulltext search is used, there only is one group. It also doesn't
make much sense when there is just one month group as well.
Closes: #1255
> Disable "group by month" option when there is only one group

- modules/restserver/src/main/scala/docspell/restserver/routes/AttachmentRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/ShareAttachmentRoutes.scala
- project/Dependencies.scala
The pdfjs distribution contains a standalone viewer already.
> Replace viewerjs with pdfjs viewer

- modules/webapp/src/main/elm/Comp/BoxQueryView.elm
- modules/webapp/src/main/elm/Comp/SearchMenu.elm
- modules/webapp/src/main/elm/Comp/TagSelect.elm
- modules/webapp/src/main/elm/Page/Share/Data.elm
- modules/webapp/src/main/elm/Page/Share/Update.elm
The order of tags is based on their overall counts and doesn't change
when tag association changes (due drag and drop) or the search.
Closes: #1318
> Fix sorting of tags in search menu

- docker/docker-compose/docker-compose.yml
The missing dash resulted in solr sending a DNS query each minute that returned NxDomain.
In my case they looked like this: "f.base.domain" with base.domain being the base domain set for local DNS.
> Fixed typo

- modules/joex/src/main/scala/docspell/joex/process/ExtractArchive.scala
Some other filetypes, like office documents, are also zip file. To
distinguish these without unpacking them, the file extensions is
checked.
Fixes: #1365
> Compare zip file exstension case insensitive

- modules/webapp/src/main/elm/Comp/ItemDetail/SingleAttachment.elm
- modules/webapp/src/main/elm/Data/UiSettings.elm
Since some browsers (safari and some mobile ones) don't update their
ui when the src attribute of an embed element changes, an iframe is
used now. But only for the "cross browser" variant.
Fixes: #1210
> Use iframe for cross-browser pdf view (pdfjs)

- modules/logging/scribe/src/main/scala/docspell/logging/impl/ScribeConfigure.scala
- modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
- modules/restserver/src/main/scala/docspell/restserver/webapp/TemplateRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/webapp/Templates.scala
- modules/webapp/src/main/elm/Comp/NotificationHookForm.elm
- modules/webapp/src/main/elm/Comp/UiSettingsForm.elm
- modules/webapp/src/main/elm/Page/Dashboard/SideMenu.elm
- use a one-line log format
- load templates only once
- fixed typos
- fix reset timezone in ui settings
- hide bookmarks headline if there are none
> Minor improvements

- modules/common/src/main/scala/docspell/common/ScanMailboxArgs.scala
- modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/routes/ScanMailboxRoutes.scala
- modules/webapp/src/main/elm/Comp/ScanMailboxForm.elm
- modules/webapp/src/main/elm/Messages/Comp/ScanMailboxForm.elm
We have now tried implementing a first version for recursive mailbox scanning.
At the moment, it is controlled by a new checkbox in the Scan Mailbox Task settings.
This depends on our changes to emil (https://github.com/eikek/emil/pull/293), but from our tests, it seems to work quite nicely now.
One problem we have left is how to handle database migration. The JSON parameters for scan-mailbox tasks is stored in a text field in the database, so adding a new "scanRecursively: false" parameter is probably not an option.
We thought the next logical thing was to simply make the new `scanRecursively` parameter optional, with a default value of false (previous behavior) - but that didn't work either, because then the JSON decoder complained that the field was missing. (Apparently, optional only …
> Add a recursive mail folder scan option to ScanMailboxTask

- build.sbt
A very small fix to change an accidentally generated Windows file separator ("\\") to a generic file-separator for resources ("/") to avoid malformed String escapes.
> Source generation build fix with backslash file-separator

- modules/store/src/main/resources/db/fixups/postgresql/V1.33.0__fix_reorganize_files.sql
- modules/store/src/main/scala/docspell/store/impl/StoreImpl.scala
- modules/store/src/main/scala/docspell/store/migrate/FlywayMigrate.scala
- modules/store/src/test/scala/docspell/store/StoreFixture.scala
- modules/store/src/test/scala/docspell/store/migrate/H2MigrateTest.scala
- modules/store/src/test/scala/docspell/store/migrate/MariaDbMigrateTest.scala
- modules/store/src/test/scala/docspell/store/migrate/PostgresqlMigrateTest.scala
> Fix previously published db migration

- nix/module-server.nix
Currently only Solr is supported.
> Add support for Postgres FTS in REST Server Nix module

- modules/fts-psql/src/test/scala/docspell/ftspsql/MigrationTest.scala
- modules/fts-psql/src/test/scala/docspell/ftspsql/PsqlFtsClientTest.scala
- modules/joex/src/main/resources/reference.conf
- modules/logging/api/src/main/scala/docspell/logging/LogConfig.scala
- modules/logging/api/src/main/scala/docspell/logging/LogEvent.scala
- modules/logging/scribe/src/main/scala/docspell/logging/impl/ScribeConfigure.scala
- modules/logging/scribe/src/test/scala/docspell/logging/TestLoggingConfig.scala
- modules/restserver/src/main/resources/reference.conf
- modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/LogEvent.scala
- modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/LogSink.scala
- modules/scheduler/impl/src/main/scala/docspell/scheduler/impl/QueueLogger.scala
- website/site/content/docs/configure/main.md
- Log levels of specific loggers can be defined in the config
file (doesn't work with env variables)
- Log events of background tasks carry now additional data
> Improve logging configuration

- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/ItemRoutes.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/ShareSearchRoutes.scala
- modules/webapp/src/main/elm/Data/Items.elm
The server defines a `limit` value and search requests are capped to
this limit if their requested value exceeds it. If this happens it is
now returned with the search response (clients can print a warning).
Closes: #1358
> Include limit-capped flag with search response

- docker/dockerfiles/restserver.dockerfile
This is an attempt to fix #1712. First tests seem to be ok, no crashes anymore. However I will keep using the image for the next few hours, upload some new data and see whether I encounter any issues. Will report back. In the meantime: I made some changes to the image:
- set openjdk17 for all platforms because it is a LT supported jre/jdk version and works with Scala 3.2.18
- use `curl` for downloading the app `.zip` because I had troubles building the image, `wget` failed during build process. I guess that it doesn't follow redirects because I first had the same issue with `curl` but with the `-L` flag it worked
- update alpine version, however I think we could even use the `3` tag so that we always get the newest minor version, what do you think?
If you like I can also adjust the `joex` …
> restserver docker image: set jdk17 for all platforms

- modules/backend/src/main/scala/docspell/backend/PasswordCrypt.scala
- modules/backend/src/main/scala/docspell/backend/auth/Login.scala
- modules/backend/src/main/scala/docspell/backend/ops/OCollective.scala
- modules/restserver/src/main/resources/reference.conf
- modules/restserver/src/main/scala/docspell/restserver/ConfigFile.scala
- modules/restserver/src/main/scala/docspell/restserver/RestAppImpl.scala
- modules/restserver/src/main/scala/docspell/restserver/RestServer.scala
- modules/restserver/src/main/scala/docspell/restserver/auth/OpenId.scala
- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
- modules/restserver/src/main/scala/docspell/restserver/routes/UserRoutes.scala
- modules/store/src/main/scala/docspell/store/records/RUser.scala
- project/Dependencies.scala
- website/site/content/docs/configure/authentication.md
A new config allows to treat an account same independent where it was created (openid or local).
> Allow to authenticate with the same account from different sources

- docker/dockerfiles/joex.dockerfile
- docker/dockerfiles/restserver.dockerfile
The explicit install was added earlier due to a broken zlib package (see issue #1517). This has now been fixed for a while in alpine and can be removed.
> Remove explicit install of zlib

- nix/checks/configuration-test.nix
- nix/modules/joex.nix
- nix/modules/server.nix
This commit adds a new option for joex and server modules - extraConfig. Its main use-case is to specify options that are present in docspell but not (perhaps, yet) defined in the modules.
> nix: add extraConfig option

- modules/convert/src/main/scala/docspell/convert/Conversion.scala
It must honor the configuration when doing html->pdf.
Found in #1895
> Fix html conversion for text files

- nix/checks/configuration-test.nix
- nix/checks/solr.nix
- nix/dev-vm/default.nix
- nix/flake.lock
- nix/flake.nix
- nix/modules/joex.nix
- website/site/content/docs/dev/development.md
Wkhtmltopdf is deemed insecure and requires a full build of qtwebengine. I am working on replacing wkhtmltopdf with weasyprint in Nix module definitions.
See #1873 for more background
> nix: replace wkhtmltopdf with weasyprint

- build.sbt
- project/Dependencies.scala
- project/TestSettings.scala
Must not be `compile->test` as this pulls in test dependencies of the other project. Also improves on `withTestSettingsDependsOn` and removes junit dependency from stanfordnlp-core.
Issue: #1856
> Fix bad defined dependency

- modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
Fixes logging the error (the effect was not evaluated before) and also distinguishes this case from having no files in the request.
Closes: #1976
> Improve error reporting when a file cannot be stored

- docker/docker-compose/docker-compose.yml
- docker/dockerfiles/joex.dockerfile
- modules/analysis/src/main/scala/docspell/analysis/date/DateFind.scala
- modules/analysis/src/main/scala/docspell/analysis/date/MonthName.scala
- modules/common/src/main/scala/docspell/common/Language.scala
- modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala
- modules/fts-solr/src/main/scala/docspell/ftssolr/Field.scala
- modules/fts-solr/src/main/scala/docspell/ftssolr/SolrSetup.scala
- modules/webapp/src/main/elm/Data/Language.elm
- modules/webapp/src/main/elm/Messages/Data/Language.elm
- website/site/content/docs/install/prereq.md
this pr contains
- update to `solr` in `docker-compose.yml` to enable `analysis-extras` module for `icu` tokenizer
- add `Khmer` lang according to the [guide](https://docspell.org/docs/dev/add-language/) but skip the adding test step
- update docs about `solr` in https://docspell.org/docs/install/prereq/ that also need `extra-analysis` module in order for text analysis to be working for `khmer` language
- update `joex.dockerfile` to add khmer font and tesseract khmer model
> add khmer lang

- modules/addonlib/src/main/scala/docspell/addons/AddonExecutionResult.scala
- modules/addonlib/src/test/scala/docspell/addons/AddonExecutorTest.scala
When debugging a pure addon that returns invalid JSON, I was getting this error message:
```
joex 2023.11.07 14:02:43:0000 [io-comp...] [WARN ] docspell.scheduler.impl.SchedulerImpl.wrapTask:283 - Task failed with permanent error
joex java.lang.Exception: Addon execution failed. Do not retry, because some addons were impure.
joex 	at docspell.joex.addon.AddonTaskExtension$AddonExecutionResultOps.raiseErrorIfNeeded(AddonTaskExtension.scala:23)
joex 	at docspell.joex.addon.ItemAddonTask$.$anonfun$apply$4(ItemAddonTask.scala:49)
joex 	at cats.data.OptionT.$anonfun$flatMap$1(OptionT.scala:207)
joex 	at scala.Option.fold(Option.scala:263)
joex 	at cats.data.OptionT.$anonfun$flatMapF$1(OptionT.scala:220)
joex 	at cats.effect.IOFiber.succeeded(IOFiber.scala:1202)
joex 	at …
```
> Fix AddonExecutionResult monoid identity

- modules/fts-psql/src/main/scala/docspell/ftspsql/FtsRepository.scala
Thanks to @eikek for the suggestion. This PR replaces all occurrences of `sql""` with `fr""` (cf.
[interpolators](https://tpolecat.github.io/doobie/docs/08-Fragments.html#whitespace-handling).
Fixes: #2367
> Replace `sql""` with `fr""` to ensure trailing spaces

- modules/backend/src/main/scala/docspell/backend/BackendCommands.scala
- modules/common/src/main/scala/docspell/common/bc/ItemAction.scala
- website/src/main/scala/docspell/website/AddonOutputExample.scala
This allows addons to set or remove the due date, by outputting the following structure:
```
{ "duedate": 1707908400000, "action": "set-due-date" }
```
Alternatively, you may set `duedate` to `null` to remove a due date.
Thanks to @eikek and @v6ak for the handholding!
> Add logic to set due date from addons, based on #2362

- modules/addonlib/src/main/scala/docspell/addons/out/NewFile.scala
- modules/addonlib/src/main/scala/docspell/addons/out/NewItem.scala
- modules/backend/src/main/scala/docspell/backend/ops/OUpload.scala
- modules/common/src/main/scala/docspell/common/ProcessItemArgs.scala
- modules/joex/src/main/scala/docspell/joex/addon/ItemAddonTask.scala
- modules/joex/src/main/scala/docspell/joex/process/CreateItem.scala
- modules/joex/src/main/scala/docspell/joex/process/ItemData.scala
- modules/joex/src/main/scala/docspell/joex/process/ReProcessItem.scala
- modules/joex/src/main/scala/docspell/joex/scanmailbox/ScanMailboxTask.scala
- modules/restapi/src/main/resources/docspell-openapi.yml
- modules/restserver/src/main/scala/docspell/restserver/conv/Conversions.scala
- modules/store/src/main/scala/db/migration/common/MigrateCollectiveIdTaskArgs.scala
- project/plugins.sbt
- website/site/content/docs/dev/adr/0009_convert_office_docs.md
- website/src/main/scala/docspell/website/AddonOutputExample.scala
- website/src/main/scala/docspell/website/ItemArgsExample.scala
- website/src/main/scala/docspell/website/ItemDataExample.scala
Allows to add some custom arbitrary json to the upload request which then gets passed through processing and ends up in the notification request. The intention is that addons and event consumers can use it for post processing.
Refs: #2334
> Custom processing data

- modules/webapp/src/main/webjar/docspell.js
Updated http4s component fixed idleTimeout between backend and proxy / client that requires now to send keep-alive messages from client to backend to prevent a timeout after 60s.
This resolves #2497.
> fix(webapp): downstream keep-alive events to backend preventing timeout

- website/site/content/docs/dev/add-language.md
- website/site/content/docs/install/download_run.md
This pull request is to resolve #2485 by providing technical documentation for the backup and restore process of the recommended database, PostgreSQL. 
I tried to reflect the current content style. Please let me know if any changes are needed to merge.
> Add documentation for backup and restore process for PostgreSQL.

- docker/dockerfiles/joex.dockerfile
- docker/dockerfiles/restserver.dockerfile
See #2504, alpine edge introduced a version of tesseract that is problematic to use from within docspell
> Change docker base images to 3.19.1

- website/site/content/docs/dev/documentation.md
It took me a bit more effort than I expected to figure out how to just contribute to the documentation, so I went ahead and wrote a page on the documentation website to complement the existing documentation on contributing and the website.
> Add page to website about contributing to docs

- nix/modules/joex.nix
- nix/modules/server.nix
"Package" option allows specifying the derivation that will be used for the systemd service. Works the same way as `services.<name>.package` in NixOS. By default picks the docspell packages from pkgs instance -- same behavior as prior to this commit
Closes #2627
> Add package option to Nix modules

- modules/joex/src/main/resources/reference.conf
The argument mappings are part of the command configuration.
Small fixup for #2505
> Move arg-mappings underneath `command` section

- modules/joex/src/main/resources/reference.conf
This resolves #2667 item 2 to make better default compatibility for optical character recognition of CJK pdf documents.
> Add Japanese Mapping for OCR Optimization

- nix/modules/joex.nix
- nix/modules/server.nix
Update the NixOS module to handle config files more securely.
This addresses some of the low-hanging fruit identified in #2451 
Instead, write to `/etc/docspell-restserver.conf` and `/etc/docspell-joex.conf` readable only by the docspell user.
Allow the user to specify the path to a config file. They can use this to point to a file they've secured with their preferred secret management scheme (to avoid leaking sensitive info in the nixos configuration itself).
Only generate a config file if this option is left unspecified.
___
Example usage:
https://codeberg.org/ivanbrennan/nixos-config/commit/0d34b183dfe3e04421cb6044e67d974b83260630
> Nix module: secure config file

- modules/joex/src/main/resources/reference.conf
> Remove `--optimize-size` option from default weasyprint

- modules/restserver/src/main/scala/docspell/restserver/http4s/ContentDisposition.scala
this reencodes the filename as UTF-8, which is probably a safe bet.
this should close #2825
> Use http4s' new Part.filename method
